[package]
name = "DespawnEngine"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
vulkano = { version = "0.35.1", features = ["macros"] }
vulkano-shaders = "0.35.0"
winit = "0.30.11"